spring.application.name=nefes
spring.datasource.url=jdbc:postgresql://localhost:5432/nefes_db
spring.datasource.username=postgres
spring.datasource.password=190504
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Gemini Api Configuration
gemini.api.key=AQ.Ab8RN6Lh3pki-7u11fokUPWeC5W2ty8PNT9-jfPRR4UdHhs8lw
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent